#登陆相关配置
login:
  #开放的模拟登陆api服务器地址
  api: "http://47.92.228.120:8080/wisedu-unified-login-api-v1.0/api/login"
#用户组配置
users:
  #单个用户配置
  - user:
      #username 只能学号或者工号 注意是金智校园的账号和密码
      username: ''
      #password 密码
      password: ''
      #address 定位地址，定位信息请按真实地址填写，如不真实将付法律责任，格式为：中国xx省xx市xx区xx街道/xx路
      address: 四川省成都市锦江区春熙路
      #email 接受通知消息的邮箱
      email: 1029789402@qq.com
      #school 学校全称
      school: 四川信息职业技术学院
  #多用户配置，将下面的注释去掉即可，如果有表单内容有图片，不建议使用多用户配置
#  - user:
#      #username 学号或者工号
#      username: 
#      #password 密码
#      password: 
#      #address 地址
#      address: 中国四川省成都市金牛区一环路北1段-129号-附9号
#      #email 接受通知消息的邮箱
#      email: 1029789402@qq.com
#      school: 四川信息职业技术学院
#今日校园相关配置
cpdaily:
  #表单组默认选项配置
  defaults:
    #表单默认选项配置，按顺序，注意，只有标必填项的才处理
    - default:
        title: 当前体温
        type: 2
        value: <37.3℃
    - default:
        title: 实测体温（℃）
        type: 1
        value: '36'
    - default:
        title: 当前身体状况
        type: 2
        value: 正常
    - default:
        title: 近14天是否去过疫情中、高风险区
        type: 2
        value: 否
    - default:
        title: 近14天是否接触过疑似或确诊病例
        type: 2
        value: 否
    - default:
        title: 本人是否承诺以上信息如实填写，准确无误
        type: 2
        value: 是